### ISSUE TITLE
Consider releasing new version

### ISSUE THREAD

**Issue by nphmuller** [mosch/react-avatar-editor#305]
When using the latest version of react-avatar-editor, React threw the following warning: 
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.` After tracking down the error (which was hard, because the component name wasn't right because of minized js files), it turned out to be react-avatar-editor. Good news is that this error has already been solved by https://github.com/mosch/react-avatar-editor/pull/303

Can you please consider releasing a new version with this fix, so React will no longer throw this warning.

**Comment by mosch** [comment]
Hey there, I'm working on an internal refactoring to resolve these issues right now.

**Comment by mosch** [comment]
I just released 12.0.0-beta.0 – and supper happy to get feedback on this.

**Comment by SCasarotto** [comment]
Based on [this test](https://codesandbox.io/s/loving-hofstadter-gwbyz?fontsize=14) and trying to update it in my library [react-tec](https://github.com/SCasarotto/react-tec) this patch didn't fix it. Click the test to see the following error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `App`.
```

**Comment by mattmacpherson** [comment]
Yeah, I'm having the same issue as @SCasarotto

**Comment by mattmacpherson** [comment]
@SCasarotto I fixed our issue. You're probably still on an earlier version of React. If so, install `react-avatar-editor@11.0.7`. Move to the version 12 when you update to React 16.

**Comment by SCasarotto** [comment]
@mattmacpherson, You seem to be right. Reverting back to 11.0.7 with an updated React did just fine. However, I am still seeing the warning @nphmuller mentioned.

**Comment by erikhuisman** [comment]
Strict mode still gives a little warning. 

There's already a ticket for it:  
https://github.com/mzabriskie/react-draggable/issues/440

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in canvas (created by AvatarEditor)
    in DraggableCore (created by AvatarEditor)
    in AvatarEditor (at avatar.js:112)
```
